# Default values for hubs-ce.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  domain: &HUBS_DOMAIN "meta-hubs.org"
  adminEmail: &ADMINEMAIL "info@virtualmente.com"
  gcp: 
    persistent:
      enabled: false
      storage: 50Gi
      volumeHandle: "modeInstance/FILESTORE_INSTANCE_LOCATION/FILESTORE_INSTANCE_NAME/FILESTORE_SHARE_NAME"
      volumeAttributes:
        ip: FILESTORE_INSTANCE_IP
        volumeName: FILESTORE_SHARE_NAME
  aws:
    efs:
      enabled: false
      isDynamicProvisioning: false
      fileSystemId: fs-000000000000

replicaCount: 1
# namespace: hcce

image:
  repository: mozillareality/hubs
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "stable-latest"

annotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

strategy:
  type: Recreate
  rollingUpdate: null

certs:
  enabled: true

env:
  - name: "IGNORE_ME"
    value: "true"



nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: haproxy
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

ns:
  enabled: false
  name: hcce

configs:
  enabled: true
  # The name of the configmap to use
  name: configs
  # The key of the configmap to use
  data:
    HUB_DOMAIN: *HUBS_DOMAIN
    ADM_EMAIL: *ADMINEMAIL
    # Get the following from render_helm.sh
    DB_USER: "postgres"
    DB_PASS: "123456"
    DB_NAME: "retdb"
    DB_HOST: "pgbouncer"
    DB_HOST_T: "pgbouncer-t"
    EXT_DB_HOST: "pgsql"
    PGRST_DB_URI: "postgres://postgres:123456@pgbouncer/retdb"
    PSQL: "postgres://postgres:123456@pgbouncer/retdb"
    SMTP_SERVER: "live.smtp.mailtrap.io"
    SMTP_PORT: "2525"
    SMTP_USER: "smtp@mailtrap.io"
    SMTP_PASS: "75d981b1a58f10aa3d54daa7ab2343a4"
    SMTP_FROM: "hello@meta-hubs.org"
    NODE_COOKIE: "node-hubs-ce"
    GUARDIAN_KEY: "guardian-key"
    PHX_KEY: "phx-key"
    SKETCHFAB_API_KEY: "?"
    TENOR_API_KEY: "?"
    PERMS_KEY: '-----BEGIN PRIVATE KEY-----\\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDn8A2XsX/vYDOm\\nd79QhxHAaP8GTGX4ctPtTYzJNYJAAshG/3QddqHbb0Am6AaRalWygEYsEseqt1d9\\nV3BnckwCCjNEVKwLYlv3eutcDn9sRcXmIGXwmXTuvAnvnyj+8lawi0mghBufQBa5\\n0hBgtF053wuxmu4ez0ZbaGsQDX2Yxjnbx00aOdE+w6tS9OGgIS5ox2SFwdCuOCHp\\nooROVhdV2RKKf+tK3wvs/DTGo5IcNK5iBErHABqOVkmPY2HlWlDgDdALFfuNK8Zb\\n6OIdmSLL1Ywc6nhcu1OPnQPVVSRADG+Rpn3frnBrw7G2p/kobtRlXqPOXNevrKXG\\nW4otkv3ZAgMBAAECggEBAMd8GUTCHsYU2PexgLPTKDp0U/vn08Bnis1MaO1Z/2fs\\nvLML3aPFuBqSyftsjtGdQo3fc/tOP7seK7qbbQscLDGI8mUv6jV0aKMnbqzjr0bB\\nkB+I+ASDCCaZRnZ5TvpQFq2Lb00Gsvc6WRGDkiCKoLA4ncco+Os43UubOJI6+C5f\\nlJN9V6nKmVoFCGE2PBv4o3edu3A0wontCh+BwgWfWpBOQFn8SMLJ5MHk3XrkOxzV\\n06WB2/g/R3KPq3HdIkGTpZ5uDW8/FJDozd5z5Aep/2jP+VRbR8C9+sUKsMfBNbeB\\nWPuBVa//nvzFTSKBxkFuryWFTb7tKXN5UA4h7yZ3JIECgYEA9Ntll+w1PXX9N7c0\\nimQ39vTVsFcC82G6ja5/zMF/8xbHhgPVORYZhcNw1Nl9VSF+a3h81n/35nUkn9ou\\nfc8c7SoXpYO52iRZUZ5ZKJPf8TQWVJtQ48XE+3cZAKe9vNYTcuxVwOe30M+nNtYY\\nVuI1EZ8LX8SLRYYQrwnTJjIopLECgYEA8n4lMHnr6S2qodBujZHPA4W5T0taRIqU\\n4KauyeITyOWZPeZQ3iDUqLGKr+3LrD/0VtXBx9f26i79KWfghRlqNKwjs5Of5JsP\\ncB2rLnTBIdkBHsn8mzvqsBl4zMMr0ss36ySSRgQwKXFowfbVdDdjZpZKYrdcUAKj\\nZpGBTeTn1akCgYEAxvCGv4OT0ibOIHmCf7pjWgucntRjOlk52Clh/ntsuJXWcEUm\\n9WXGQM8FGnrGgOdgrnLLgv+f66dbpWEAiwk+qFadtcWrt9f2lgDA0d4rge7fAcjb\\nVOR3YhRmxQiEeSu5y5LHLZ9W0poUctJKHjVWBsYg2KN4wHjnjz+9RXhVW1ECgYEA\\nxq/5RMkBNSPHxaIEk1a/KgGtnnz9T1/FMHUijiQBVgBaGU/XPsnjtP0Tx6at1Urp\\npySqDFa155fssqBEJIp4bQQGlKMGxccPVSvaEMx1Woh11IZnxcHIP9X/Frdr9uGv\\nxalHeLsBw1M7JIJcz0Z62ZmXBV978crXm7jpG6vNEVECgYA1kFHLm/K0OW+lJNtq\\nRQsw7jXpIWfR3gr8MKudE3SJi/nX7/VZlIH9eCdEq5jg61dNTe3WZhHSUPF8fGyt\\n5qEScr1CttlEqkHLXWfaGeJI96On7B8BpYgFySiBu634uhb5yhMH27Y0V+416TeM\\nI/LBlLGVzdmTNu8gsM8v9ijQfQ==\\n-----END PRIVATE KEY-----\\n'
    PERMS_KEY: '-----BEGIN PRIVATE KEY-----\\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDn8A2XsX/vYDOm\\nd79QhxHAaP8GTGX4ctPtTYzJNYJAAshG/3QddqHbb0Am6AaRalWygEYsEseqt1d9\\nV3BnckwCCjNEVKwLYlv3eutcDn9sRcXmIGXwmXTuvAnvnyj+8lawi0mghBufQBa5\\n0hBgtF053wuxmu4ez0ZbaGsQDX2Yxjnbx00aOdE+w6tS9OGgIS5ox2SFwdCuOCHp\\nooROVhdV2RKKf+tK3wvs/DTGo5IcNK5iBErHABqOVkmPY2HlWlDgDdALFfuNK8Zb\\n6OIdmSLL1Ywc6nhcu1OPnQPVVSRADG+Rpn3frnBrw7G2p/kobtRlXqPOXNevrKXG\\nW4otkv3ZAgMBAAECggEBAMd8GUTCHsYU2PexgLPTKDp0U/vn08Bnis1MaO1Z/2fs\\nvLML3aPFuBqSyftsjtGdQo3fc/tOP7seK7qbbQscLDGI8mUv6jV0aKMnbqzjr0bB\\nkB+I+ASDCCaZRnZ5TvpQFq2Lb00Gsvc6WRGDkiCKoLA4ncco+Os43UubOJI6+C5f\\nlJN9V6nKmVoFCGE2PBv4o3edu3A0wontCh+BwgWfWpBOQFn8SMLJ5MHk3XrkOxzV\\n06WB2/g/R3KPq3HdIkGTpZ5uDW8/FJDozd5z5Aep/2jP+VRbR8C9+sUKsMfBNbeB\\nWPuBVa//nvzFTSKBxkFuryWFTb7tKXN5UA4h7yZ3JIECgYEA9Ntll+w1PXX9N7c0\\nimQ39vTVsFcC82G6ja5/zMF/8xbHhgPVORYZhcNw1Nl9VSF+a3h81n/35nUkn9ou\\nfc8c7SoXpYO52iRZUZ5ZKJPf8TQWVJtQ48XE+3cZAKe9vNYTcuxVwOe30M+nNtYY\\nVuI1EZ8LX8SLRYYQrwnTJjIopLECgYEA8n4lMHnr6S2qodBujZHPA4W5T0taRIqU\\n4KauyeITyOWZPeZQ3iDUqLGKr+3LrD/0VtXBx9f26i79KWfghRlqNKwjs5Of5JsP\\ncB2rLnTBIdkBHsn8mzvqsBl4zMMr0ss36ySSRgQwKXFowfbVdDdjZpZKYrdcUAKj\\nZpGBTeTn1akCgYEAxvCGv4OT0ibOIHmCf3pjWgucntRjOlk52Clh/ntsuJXWcEUm\\n9WXGQM8FGnrGgOdgrnLLgv+f66dbpWEAiwk+qFadtcWrt9f2lgDA0d4rge7fAcjb\\nVOR3YhRmxQiEeSu5y5LHLZ9W0poUctJKHjVWBsYg2KN4wHjnjz+9RXhVW1ECgYEA\\nxq/5RMkBNSPHxaIEk1a/KgGtnnz9T1/FMHUijiQBVgBaGU/XPsnjtP0Tx6at1Urp\\npySqDFa155fssqBEJIp4bQQGlKMGxccPVSvaEMx1Woh11IZnxcHIP9X/Frdr9uGv\\nxalHeLsBw1M7JIJcz0Z62ZmXBV978crXm7jpG6vNEVECgYA1kFHLm/K0OW+lJNtq\\nRQsw7jXpIWfR3gr8MKudE3SJi/nX7/VZlIH9eCdEq5jg61dNTe3WZhHSUPF8fGyt\\n5qEScr1CttlEqkHLXWfaGeJI96On7B8BpYgFySiBu634uhb5yhMH27Y0V+416TeM\\nI/LBlLGVzdmTNu8gsM8v9ijQfQ==\\n-----END PRIVATE KEY-----\\n'
    PERMS_KEY: '-----BEGIN PRIVATE KEY-----\\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDn8A2XsX/vYDOm\\nd79QhxHAaP8GTGX4ctPtTYzJNYJAAshG/3QddqHbb0Am6AaRalWygEYsEseqt1d9\\nV3BnckwCCjNEVKwLYlv3eutcDn9sRcXmIGXwmXTuvAnvnyj+8lawi0mghBufQBa5\\n0hBgtF053wuxmu4ez0ZbaGsQDX2Yxjnbx00aOdE+w6tS9OGgIS5ox2SFwdCuOCHp\\nooROVhdV2RKKf+tK3wvs/DTGo5IcNK5iBErHABqOVkmPY2HlWlDgDdALFfuNK8Zb\\n6OIdmSLL1Ywc6nhcu1OPnQPVVSRADG+Rpn3frnBrw7G2p/kobtRlXqPOXNevrKXG\\nW4otkv3ZAgMBAAECggEBAMd8GUTCHsYU2PexgLPTKDp0U/vn08Bnis1MaO1Z/2fs\\nvLML3aPFuBqSyftsjtGdQo3fc/tOP7seK7qbbQscLDGI8mUv6jV0aKMnbqzjr0bB\\nkB+I+ASDCCaZRnZ5TvpQFq2Lb00Gsvc6WRGDkiCKoLA4ncco+Os43UubOJI6+C5f\\nlJN9V6nKmVoFCGE2PBv4o3edu3A0wontCh+BwgWfWpBOQFn8SMLJ5MHk3XrkOxzV\\n06WB2/g/R3KPq3HdIkGTpZ5uDW8/FJDozd5z5Aep/2jP+VRbR8C9+sUKsMfBNbeB\\nWPuBVa//nvzFTSKBxkFuryWFTb7tKXN5UA4h7yZ3JIECgYEA9Ntll+w1PXX9N7c0\\nimQ39vTVsFcC82G6ja5/zMF/8xbHhgPVORYZhcNw1Nl9VSF+a3h81n/35nUkn9ou\\nfc8c7SoXpYO52iRZUZ5ZKJPf8TQWVJtQ48XE+3cZAKe9vNYTcuxVwOe30M+nNtYY\\nVuI1EZ8LX8SLRYYQrwnTJjIopLECgYEA8n4lMHnr6S2qodBujZHPA4W5T0taRIqU\\n4KauyeITyOWZPeZQ3iDUqLGKr+3LrD/0VtXBx9f26i79KWfghRlqNKwjs5Of5JsP\\ncB2rLnTBIdkBHsn8mzvqsBl4zMMr0ss36ySSRgQwKXFowfbVdDdjZpZKYrdcUAKj\\nZpGBTeTn1akCgYEAxvCGv4OT0ibOIHmCf3pjWgucntRjOlk52Clh/ntsuJXWcEUm\\n9WXGQM8FGnrGgOdgrnLLgv+f66dbpWEAiwk+qFadtcWrt9f2lgDA0d4rge7fAcjb\\nVOR3YhRmxQiEeSu5y5LHLZ9W0poUctJKHjVWBsYg2KN4wHjnjz+9RXhVW1ECgYEA\\nxq/5RMkBNSPHxaIEk1a/KgGtnnz9T1/FMHUijiQBVgBaGU/XPsnjtP0Tx6at1Urp\\npySqDFa155fssqBEJIp4bQQGlKMGxccPVSvaEMx1Woh11IZnxcHIP9X/Frdr9uGv\\nxalHeLsBw1M7JIJcz0Z62ZmXBV978crXm7jpG6vNEVECgYA1kFHLm/K0OW+lJNtq\\nRQsw7jXpIWfR3gr8MKudE3SJi/nX7/VZlIH9eCdEq5jg61dNTe3WZhHSUPF8fGyt\\n5qEScr1CttlEqkHLXWfaGeJI96On7B8BpYgFySiBu634uhb5yhMH27Y0V+416TeM\\nI/LBlLGVzdmTNu8gsM8v9ijQfQ==\\n-----END PRIVATE KEY-----\\n'
    PERMS_KEY: '-----BEGIN PRIVATE KEY-----\\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDn8A2XsX/vYDOm\\nd79QhxHAaP8GTGX4ctPtTYzJNYJAAshG/3QddqHbb0Am6AaRalWygEYsEseqt1d9\\nV3BnckwCCjNEVKwLYlv3eutcDn9sRcXmIGXwmXTuvAnvnyj+8lawi0mghBufQBa5\\n0hBgtF053wuxmu4ez0ZbaGsQDX2Yxjnbx00aOdE+w6tS9OGgIS5ox2SFwdCuOCHp\\nooROVhdV2RKKf+tK3wvs/DTGo5IcNK5iBErHABqOVkmPY2HlWlDgDdALFfuNK8Zb\\n6OIdmSLL1Ywc6nhcu1OPnQPVVSRADG+Rpn3frnBrw7G2p/kobtRlXqPOXNevrKXG\\nW4otkv3ZAgMBAAECggEBAMd8GUTCHsYU2PexgLPTKDp0U/vn08Bnis1MaO1Z/2fs\\nvLML3aPFuBqSyftsjtGdQo3fc/tOP7seK7qbbQscLDGI8mUv6jV0aKMnbqzjr0bB\\nkB+I+ASDCCaZRnZ5TvpQFq2Lb00Gsvc6WRGDkiCKoLA4ncco+Os43UubOJI6+C5f\\nlJN9V6nKmVoFCGE2PBv4o3edu3A0wontCh+BwgWfWpBOQFn8SMLJ5MHk3XrkOxzV\\n06WB2/g/R3KPq3HdIkGTpZ5uDW8/FJDozd5z5Aep/2jP+VRbR8C9+sUKsMfBNbeB\\nWPuBVa//nvzFTSKBxkFuryWFTb7tKXN5UA4h7yZ3JIECgYEA9Ntll+w1PXX9N7c0\\nimQ39vTVsFcC82G6ja5/zMF/8xbHhgPVORYZhcNw1Nl9VSF+a3h81n/35nUkn9ou\\nfc8c7SoXpYO52iRZUZ5ZKJPf8TQWVJtQ48XE+3cZAKe9vNYTcuxVwOe30M+nNtYY\\nVuI1EZ8LX8SLRYYQrwnTJjIopLECgYEA8n4lMHnr6S2qodBujZHPA4W5T0taRIqU\\n4KauyeITyOWZPeZQ3iDUqLGKr+3LrD/0VtXBx9f26i79KWfghRlqNKwjs5Of5JsP\\ncB2rLnTBIdkBHsn8mzvqsBl4zMMr0ss36ySSRgQwKXFowfbVdDdjZpZKYrdcUAKj\\nZpGBTeTn1akCgYEAxvCGv4OT0ibOIHmCf3pjWgucntRjOlk52Clh/ntsuJXWcEUm\\n9WXGQM8FGnrGgOdgrnLLgv+f66dbpWEAiwk+qFadtcWrt9f2lgDA0d4rge7fAcjb\\nVOR3YhRmxQiEeSu5y5LHLZ9W0poUctJKHjVWBsYg2KN4wHjnjz+9RXhVW1ECgYEA\\nxq/5RMkBNSPHxaIEk1a/KgGtnnz9T1/FMHUijiQBVgBaGU/XPsnjtP0Tx6at1Urp\\npySqDFa155fssqBEJIp4bQQGlKMGxccPVSvaEMx1Woh11IZnxcHIP9X/Frdr9uGv\\nxalHeLsBw1M7JIJcz0Z62ZmXBV978crXm7jpG6vNEVECgYA1kFHLm/K0OW+lJNtq\\nRQsw7jXpIWfR3gr8MKudE3SJi/nX7/VZlIH9eCdEq5jg61dNTe3WZhHSUPF8fGyt\\n5qEScr1CttlEqkHLXWfaGeJI96On7B8BpYgFySiBu634uhb5yhMH27Y0V+416TeM\\nI/LBlLGVzdmTNu8gsM8v9ijQfQ==\\n-----END PRIVATE KEY-----\\n'
    PGRST_JWT_SECRET: '{"kty":"RSA","n":"5_ANl7F_72Azpne_UIcRwGj_Bkxl-HLT7U2MyTWCQALIRv90HXah229AJugGkWpVsoBGLBLHqrdXfVdwZ3JMAgozRFSsC2Jb93rrXA5_bEXF5iBl8Jl07rwJ758o_vJWsItJoIQbn0AWudIQYLRdOd8LsZruHs9GW2hrEA19mMY528dNGjnRPsOrUvThoCEuaMdkhcHQrjgh6aKETlYXVdkSin_rSt8L7Pw0xqOSHDSuYgRKxwAajlZJj2Nh5VpQ4A3QCxX7jSvGW-jiHZkiy9WMHOp4XLt1OPnQPVVSRADG+Rpn3frnBrw7G2p/kobtRlXqPOXNevrKXGluKLZL92Q","e":"AQAB"}'
    
defaultCert:
  enabled: true
  name: cert-hcce
  data:
    tls.crt: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyRENDQVpRQ0NRQ2I2ai9ZT2dTR0RUQU5CZ2txaGtpRzl3MEJBUXNGQURBWU1SWXdGQVlEVlFRRERBMXQKWlhSaExXaDFZbk11YjNKbk1CNFhEVEkyTURFek1URTFNRFV6TVZvWERUSTNNREV6TVRFMU1EVXpNVm93R0RFVwpNQlFHQTFVRUF3d05iV1YwWVMxb2RXSnpMbTl5WnpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQUwxU1lKcXdlbDNCRmVWbmliVm43aDIxUkFvR3gydWtiUlRMUElYS0V0YUxHb29hOGtUYTBYbkwKYXZRczVGc0cvTnVwZDJFeEVRSDBQUTdJcFZwVTluRUZkR2lTSVVrYndwWXVaeXdqRWlxSjB5RnlpLzd3M09Iagp3a2VnNDZ2a1hVK0JtdGVlZ3A2c3U2OVBWVUVhWTF6Q1hRZ0hyMFhUU2EySXBqQ25Ia0lzN3p3TXVqb001ZW5UCitOcWFCTmw2eU9reVdaSUl6ZXB0eWdRS25uczRVaENUQU1lamtOM3pPTHFveHV0YnpCMmpISVpkeHNMRGcrL1UKSEsvWkl4WmZ4NWJvVXdLd1VBS1F0b1lJMVNXOExKbXowLyt0bXV0L2g3RDlkNXM3WmlnSzhodm5BVS9xMDVQYQp6aE10ZEdUREhkQ09FWG1DbmNyTW5BeFJLUGp2V1prQ0F3RUFBVEFOQmdrcWhraUc5dzBCQVFzRkFBT0NBUUVBCnI0bjVUTEcrUVdCam5YdnA1bENSRjVWYUJEa3R2ZlZjSDhFTzlJWnFqcjBud0xQTUVFVVV3ZHJjMlFiVnBjSWIKcDBNRWZXNTFSWnNVS21WNVV1a2taWjRXYlVqWnpCbnlaekdVcEwvbkc4UnBKKzhCa0tYYTZ5RkI0N0FORGc0SgpTYjIwSWdQdXd6Y1prNVNHcjRaYzRMbVBhWlY0VjZaMWI0RUxQS1VONW9jZmpxNXFIZ0cvckE3UzFSZmwvRHk5Cm9kdWlQZUFkNzBSNGEzVStrRnRIYitudGJXYVpXQklHcjJKSWo5a0ppK2J3dmJiV0ZZWitKQ2JhaFM4ejdLcWMKblF4cEVUMEUxUjhsbzN4ZTZhTG5ORk9yaTVra2NBVFJNMkZIcHFIc1pkaDRXdzRSOEZUcTA0ZDBFYjc1c245YQpyeUlORUFpQ1FvTzBwZXg5QzRoNDJ3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo='
    tls.key: 'LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQzlVbUNhc0hwZHdSWGwKWjRtMVorNGR0VVFLQnNkcnBHMFV5enlGeWhMV2l4cUtHdkpFMnRGNXkycjBMT1JiQnZ6YnFYZGhNUkVCOUQwTwp5S1ZhVlBaeEJYUm9raUZKRzhLV0xtY3NJeElxaWRNaGNvdis4TnpoNDhKSG9PT3I1RjFQZ1pyWG5vS2VyTHV2ClQxVkJHbU5jd2wwSUI2OUYwMG10aUtZd3B4NUNMTzg4RExvNkRPWHAwL2phbWdUWmVzanBNbG1TQ00zcWJjb0UKQ3A1N09GSVFrd0RIbzVEZDh6aTZxTWJyVzh3ZG94eUdYY2JDdzRQdjFCeXYyU01XWDhlVzZGTUNzRkFDa0xhRwpDTlVsdkN5WnM5UC9yWnJyZjRldy9YZWJPMllvQ3ZJYjV3RlA2dE9UMnM0VExYUmt3eDNRamhGNWdwM0t6SndNClVTajQ3MW1aQWdNQkFBRUNnZ0VBUEJ3VG9BbTRVRndsMzVob0dMak8yWS9iOG5NRWppQytvWU9GeTlURTltbGsKRzhWQ2Rxb2pLRkIxdk9Fai8rTFFGYzVRb1FNN0t5dW8xekROajBpNmxsZnRCZWFmdXQ2ZGdhRnFFSkZ5Q3grSApjVzgxRTlUVnpNTEx4SUpJeHlMU25aUEEzZ1R0NUFOajg5MTBiQjg4dlE3WkN0dWx3cjI2L3VZTUhoWnhmUURMCkFiMGdvNGt3bXNUbjZqWEFuZWduRWc1MGoxaVV2RVFuNnZ1QS9va2dnbkIzb25KTkIwMXhqaUwzQWFkeXNLQTYKR1d0MFpTOUxFdFgyVHgrdFUzWDk5Y0VSbGxKc3oyL0VoUHFrYzRTRnNrZkpndXJxTVhyOFFndHlPNjVFeC9Lbwo3TzU2UWhabGtDcFI2TGVTUk9XcHpVZWNWYWxSZW1sbzVHanFucm5rZ1FLQmdRRHdGT1o0WXphYy9qRmg0Z1pTCjJtZnRsNjdCN2QrcHFHTGhjSmw5TjZocWx1aWcwejNqZ0Fsc1hlU3ZtdWJWdFpmdTJ3bXJOalFPbEFBYjVzV1MKeXg0TmZzUlJaWjhBV1JEOHVWcTNHOUtoejhaVTZ2T3l5VmZBYkF0R1VhR3BUOUZHeDBNenpTZUtPNXNDTFFRQQpwOXBaZ1pENGRmQUpQdjZEcjgzOS9SenVKUUtCZ1FESjMrT1lXSEJFV0NEdXhwczlPSXNxNm42d0xRRTYxZlppCmlKSzk3ZWhNNS95SWVDbWxMWTZNaWk2ZTRxS1Q0aWJOU3M0VTJTL2l4NWJlTFJtRFEzREJoMFhmUld2U2l1NW4KWEVwbGhGYmdQRHFEK0FmTG9vamFHdE1KdTE5RXNQWUtuQnBRbXF2MjRpUm92OElyUGowaHhsdjFVZGtwSHJkUgprb1pVVTNaQlpRS0JnUURmbXFlNU1yYVg2OHcwblY1RVpyVHJQaDMrOHowZ2QvdDRldllLQVArMEhzK1Zrb21PCnpSNTV0czJhbkl3b09WVERtM0JhN1VYNDJmRnNDeml5NnNrWHlweXdMeFN6TDBFNkVLeWo1SjcrSkZWVm0rclQKOXVEckQvWkVUUjFqWXpySVVDaVFJNkNUQjhic2RON0llWTFOVmZhZTRzRm82eW9Ebm9jZDYxTzVuUUtCZ0ZQeApEOTlDTHZTTVBLMXMwaEpEMThKeG5WbytiSHQ5aXFUd0t5eGtwNnFLOER3QzB6WkcyalpnSXdDWU5vZ05pcHJrCmx3cWVRTVlvdmZnR2dzeE5GNjZ4UkFHU0NVS1QySXdNR1RkYkx4Q3dtcGhUWTFKdWREOVUxaG4rMnA5aWdmeHAKYXB2SHBPZlVvdFVYbjNLQnY4T3lpbnhZbTFiNDJidEdsU3F0UmNmdEFvR0JBTkZLN1JEZmpzZXI4eXo3RWdYVwpWRDNUZE01YmdIODBOMSt6K1hFWE1yT05yQ1pxN2hHaGlPTVpqVUYybWlzaEkxRkU4SDJUamF2eGRxNGpDTUplCjdpVDhmWkMzL0JRTERpZE0yb3lJTGlnQlB6RmdkbDgvMEd2dHZwRVRURzhhMHBFV3M5OEhad3lOeVJmYUE3UDUKaVZURVdGKzZPcEF3anorQkZlVC84NjBzCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K'

reticulum:

  persistence:
    enabled: true
    size: 10Gi
    storageClass: do-block-storage
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 256Mi
  extraEnv:
    SENTRY_DSN: ""
  image:
    repository: mozillareality/reticulum
    tag: "stable-latest"

spoke:
  image:
    repository: mozillareality/spoke
    tag: "stable-latest"
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

pgsql:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: do-block-storage
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

