# Default values for hubs-ce.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  domain: &HUBS_DOMAIN "meta-hubs.org"
  adminEmail: &ADMINEMAIL "info@virtualmente.com"
  gcp: 
    persistent:
      enabled: false
      storage: 50Gi
      volumeHandle: "modeInstance/FILESTORE_INSTANCE_LOCATION/FILESTORE_INSTANCE_NAME/FILESTORE_SHARE_NAME"
      volumeAttributes:
        ip: FILESTORE_INSTANCE_IP
        volumeName: FILESTORE_SHARE_NAME
  aws:
    efs:
      enabled: false
      isDynamicProvisioning: false
      fileSystemId: fs-000000000000

replicaCount: 1
# namespace: hcce

image:
  repository: registry.digitalocean.com/meta-hubs-registry/hubs
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

annotations:
  cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

strategy:
  type: Recreate
  rollingUpdate: null

certs:
  enabled: true

env:
  - name: turkeyCfg_thumbnail_server
    value: cors.{{ .Values.global.domain }}/nearspark
  - name: turkeyCfg_tier
    value: p1

imagePullSecrets:
  - name: registry-meta-hubs-registry
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: haproxy
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"

resources:
  limits:
    memory: 1Gi
  requests:
    cpu: 50m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

ns:
  enabled: false
  name: hcce

configs:
  enabled: true
  # The name of the configmap to use
  name: configs
  # The key of the configmap to use
  data:
    HUB_DOMAIN: *HUBS_DOMAIN
    ADM_EMAIL: *ADMINEMAIL
    # Get the following from render_helm.sh
    DB_USER: "postgres"
    DB_PASS: "123456"
    DB_NAME: "retdb"
    DB_HOST: "pgbouncer"
    DB_HOST_T: "pgbouncer-t"
    EXT_DB_HOST: "pgsql"
    PGRST_DB_URI: "postgres://postgres:123456@pgbouncer/retdb"
    PSQL: "postgres://postgres:123456@pgbouncer/retdb"
    SMTP_SERVER: "live.smtp.mailtrap.io"
    SMTP_PORT: "2525"
    SMTP_USER: "smtp@mailtrap.io"
    SMTP_PASS: "75d981b1a58f10aa3d54daa7ab2343a4"
    SMTP_FROM: "hello@meta-hubs.org"
    NODE_COOKIE: "node-hubs-ce"
    GUARDIAN_KEY: "guardian-key"
    PHX_KEY: "phx-key"
    SKETCHFAB_API_KEY: "?"
    TENOR_API_KEY: "?"
    PERMS_KEY: '-----BEGIN PRIVATE KEY-----\\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDn8A2XsX/vYDOm\\nd79QhxHAaP8GTGX4ctPtTYzJNYJAAshG/3QddqHbb0Am6AaRalWygEYsEseqt1d9\\nV3BnckwCCjNEVKwLYlv3eutcDn9sRcXmIGXwmXTuvAnvnyj+8lawi0mghBufQBa5\\n0hBgtF053wuxmu4ez0ZbaGsQDX2Yxjnbx00aOdE+w6tS9OGgIS5ox2SFwdCuOCHp\\nooROVhdV2RKKf+tK3wvs/DTGo5IcNK5iBErHABqOVkmPY2HlWlDgDdALFfuNK8Zb\\n6OIdmSLL1Ywc6nhcu1OPnQPVVSRADG+Rpn3frnBrw7G2p/kobtRlXqPOXNevrKXG\\nW4otkv3ZAgMBAAECggEBAMd8GUTCHsYU2PexgLPTKDp0U/vn08Bnis1MaO1Z/2fs\\nvLML3aPFuBqSyftsjtGdQo3fc/tOP7seK7qbbQscLDGI8mUv6jV0aKMnbqzjr0bB\\nkB+I+ASDCCaZRnZ5TvpQFq2Lb00Gsvc6WRGDkiCKoLA4ncco+Os43UubOJI6+C5f\\nlJN9V6nKmVoFCGE2PBv4o3edu3A0wontCh+BwgWfWpBOQFn8SMLJ5MHk3XrkOxzV\\n06WB2/g/R3KPq3HdIkGTpZ5uDW8/FJDozd5z5Aep/2jP+VRbR8C9+sUKsMfBNbeB\\nWPuBVa//nvzFTSKBxkFuryWFTb7tKXN5UA4h7yZ3JIECgYEA9Ntll+w1PXX9N7c0\\nimQ39vTVsFcC82G6ja5/zMF/8xbHhgPVORYZhcNw1Nl9VSF+a3h81n/35nUkn9ou\\nfc8c7SoXpYO52iRZUZ5ZKJPf8TQWVJtQ48XE+3cZAKe9vNYTcuxVwOe30M+nNtYY\\nVuI1EZ8LX8SLRYYQrwnTJjIopLECgYEA8n4lMHnr6S2qodBujZHPA4W5T0taRIqU\\n4KauyeITyOWZPeZQ3iDUqLGKr+3LrD/0VtXBx9f26i79KWfghRlqNKwjs5Of5JsP\\ncB2rLnTBIdkBHsn8mzvqsBl4zMMr0ss36ySSRgQwKXFowfbVdDdjZpZKYrdcUAKj\\nZpGBTeTn1akCgYEAxvCGv4OT0ibOIHmCf7pjWgucntRjOlk52Clh/ntsuJXWcEUm\\n9WXGQM8FGnrGgOdgrnLLgv+f66dbpWEAiwk+qFadtcWrt9f2lgDA0d4rge7fAcjb\\nVOR3YhRmxQiEeSu5y5LHLZ9W0poUctJKHjVWBsYg2KN4wHjnjz+9RXhVW1ECgYEA\\nxq/5RMkBNSPHxaIEk1a/KgGtnnz9T1/FMHUijiQBVgBaGU/XPsnjtP0Tx6at1Urp\\npySqDFa155fssqBEJIp4bQQGlKMGxccPVSvaEMx1Woh11IZnxcHIP9X/Frdr9uGv\\nxalHeLsBw1M7JIJcz0Z62ZmXBV978crXm7jpG6vNEVECgYA1kFHLm/K0OW+lJNtq\\nRQsw7jXpIWfR3gr8MKudE3SJi/nX7/VZlIH9eCdEq5jg61dNTe3WZhHSUPF8fGyt\\n5qEScr1CttlEqkHLXWfaGeJI96On7B8BpYgFySiBu634uhb5yhMH27Y0V+416TeM\\nI/LBlLGVzdmTNu8gsM8v9ijQfQ==\\n-----END PRIVATE KEY-----\\n'
    PERMS_KEY: '-----BEGIN PRIVATE KEY-----\\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDn8A2XsX/vYDOm\\nd79QhxHAaP8GTGX4ctPtTYzJNYJAAshG/3QddqHbb0Am6AaRalWygEYsEseqt1d9\\nV3BnckwCCjNEVKwLYlv3eutcDn9sRcXmIGXwmXTuvAnvnyj+8lawi0mghBufQBa5\\n0hBgtF053wuxmu4ez0ZbaGsQDX2Yxjnbx00aOdE+w6tS9OGgIS5ox2SFwdCuOCHp\\nooROVhdV2RKKf+tK3wvs/DTGo5IcNK5iBErHABqOVkmPY2HlWlDgDdALFfuNK8Zb\\n6OIdmSLL1Ywc6nhcu1OPnQPVVSRADG+Rpn3frnBrw7G2p/kobtRlXqPOXNevrKXG\\nW4otkv3ZAgMBAAECggEBAMd8GUTCHsYU2PexgLPTKDp0U/vn08Bnis1MaO1Z/2fs\\nvLML3aPFuBqSyftsjtGdQo3fc/tOP7seK7qbbQscLDGI8mUv6jV0aKMnbqzjr0bB\\nkB+I+ASDCCaZRnZ5TvpQFq2Lb00Gsvc6WRGDkiCKoLA4ncco+Os43UubOJI6+C5f\\nlJN9V6nKmVoFCGE2PBv4o3edu3A0wontCh+BwgWfWpBOQFn8SMLJ5MHk3XrkOxzV\\n06WB2/g/R3KPq3HdIkGTpZ5uDW8/FJDozd5z5Aep/2jP+VRbR8C9+sUKsMfBNbeB\\nWPuBVa//nvzFTSKBxkFuryWFTb7tKXN5UA4h7yZ3JIECgYEA9Ntll+w1PXX9N7c0\\nimQ39vTVsFcC82G6ja5/zMF/8xbHhgPVORYZhcNw1Nl9VSF+a3h81n/35nUkn9ou\\nfc8c7SoXpYO52iRZUZ5ZKJPf8TQWVJtQ48XE+3cZAKe9vNYTcuxVwOe30M+nNtYY\\nVuI1EZ8LX8SLRYYQrwnTJjIopLECgYEA8n4lMHnr6S2qodBujZHPA4W5T0taRIqU\\n4KauyeITyOWZPeZQ3iDUqLGKr+3LrD/0VtXBx9f26i79KWfghRlqNKwjs5Of5JsP\\ncB2rLnTBIdkBHsn8mzvqsBl4zMMr0ss36ySSRgQwKXFowfbVdDdjZpZKYrdcUAKj\\nZpGBTeTn1akCgYEAxvCGv4OT0ibOIHmCf3pjWgucntRjOlk52Clh/ntsuJXWcEUm\\n9WXGQM8FGnrGgOdgrnLLgv+f66dbpWEAiwk+qFadtcWrt9f2lgDA0d4rge7fAcjb\\nVOR3YhRmxQiEeSu5y5LHLZ9W0poUctJKHjVWBsYg2KN4wHjnjz+9RXhVW1ECgYEA\\nxq/5RMkBNSPHxaIEk1a/KgGtnnz9T1/FMHUijiQBVgBaGU/XPsnjtP0Tx6at1Urp\\npySqDFa155fssqBEJIp4bQQGlKMGxccPVSvaEMx1Woh11IZnxcHIP9X/Frdr9uGv\\nxalHeLsBw1M7JIJcz0Z62ZmXBV978crXm7jpG6vNEVECgYA1kFHLm/K0OW+lJNtq\\nRQsw7jXpIWfR3gr8MKudE3SJi/nX7/VZlIH9eCdEq5jg61dNTe3WZhHSUPF8fGyt\\n5qEScr1CttlEqkHLXWfaGeJI96On7B8BpYgFySiBu634uhb5yhMH27Y0V+416TeM\\nI/LBlLGVzdmTNu8gsM8v9ijQfQ==\\n-----END PRIVATE KEY-----\\n'
    PERMS_KEY: '-----BEGIN PRIVATE KEY-----\\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDn8A2XsX/vYDOm\\nd79QhxHAaP8GTGX4ctPtTYzJNYJAAshG/3QddqHbb0Am6AaRalWygEYsEseqt1d9\\nV3BnckwCCjNEVKwLYlv3eutcDn9sRcXmIGXwmXTuvAnvnyj+8lawi0mghBufQBa5\\n0hBgtF053wuxmu4ez0ZbaGsQDX2Yxjnbx00aOdE+w6tS9OGgIS5ox2SFwdCuOCHp\\nooROVhdV2RKKf+tK3wvs/DTGo5IcNK5iBErHABqOVkmPY2HlWlDgDdALFfuNK8Zb\\n6OIdmSLL1Ywc6nhcu1OPnQPVVSRADG+Rpn3frnBrw7G2p/kobtRlXqPOXNevrKXG\\nW4otkv3ZAgMBAAECggEBAMd8GUTCHsYU2PexgLPTKDp0U/vn08Bnis1MaO1Z/2fs\\nvLML3aPFuBqSyftsjtGdQo3fc/tOP7seK7qbbQscLDGI8mUv6jV0aKMnbqzjr0bB\\nkB+I+ASDCCaZRnZ5TvpQFq2Lb00Gsvc6WRGDkiCKoLA4ncco+Os43UubOJI6+C5f\\nlJN9V6nKmVoFCGE2PBv4o3edu3A0wontCh+BwgWfWpBOQFn8SMLJ5MHk3XrkOxzV\\n06WB2/g/R3KPq3HdIkGTpZ5uDW8/FJDozd5z5Aep/2jP+VRbR8C9+sUKsMfBNbeB\\nWPuBVa//nvzFTSKBxkFuryWFTb7tKXN5UA4h7yZ3JIECgYEA9Ntll+w1PXX9N7c0\\nimQ39vTVsFcC82G6ja5/zMF/8xbHhgPVORYZhcNw1Nl9VSF+a3h81n/35nUkn9ou\\nfc8c7SoXpYO52iRZUZ5ZKJPf8TQWVJtQ48XE+3cZAKe9vNYTcuxVwOe30M+nNtYY\\nVuI1EZ8LX8SLRYYQrwnTJjIopLECgYEA8n4lMHnr6S2qodBujZHPA4W5T0taRIqU\\n4KauyeITyOWZPeZQ3iDUqLGKr+3LrD/0VtXBx9f26i79KWfghRlqNKwjs5Of5JsP\\ncB2rLnTBIdkBHsn8mzvqsBl4zMMr0ss36ySSRgQwKXFowfbVdDdjZpZKYrdcUAKj\\nZpGBTeTn1akCgYEAxvCGv4OT0ibOIHmCf3pjWgucntRjOlk52Clh/ntsuJXWcEUm\\n9WXGQM8FGnrGgOdgrnLLgv+f66dbpWEAiwk+qFadtcWrt9f2lgDA0d4rge7fAcjb\\nVOR3YhRmxQiEeSu5y5LHLZ9W0poUctJKHjVWBsYg2KN4wHjnjz+9RXhVW1ECgYEA\\nxq/5RMkBNSPHxaIEk1a/KgGtnnz9T1/FMHUijiQBVgBaGU/XPsnjtP0Tx6at1Urp\\npySqDFa155fssqBEJIp4bQQGlKMGxccPVSvaEMx1Woh11IZnxcHIP9X/Frdr9uGv\\nxalHeLsBw1M7JIJcz0Z62ZmXBV978crXm7jpG6vNEVECgYA1kFHLm/K0OW+lJNtq\\nRQsw7jXpIWfR3gr8MKudE3SJi/nX7/VZlIH9eCdEq5jg61dNTe3WZhHSUPF8fGyt\\n5qEScr1CttlEqkHLXWfaGeJI96On7B8BpYgFySiBu634uhb5yhMH27Y0V+416TeM\\nI/LBlLGVzdmTNu8gsM8v9ijQfQ==\\n-----END PRIVATE KEY-----\\n'
    PERMS_KEY: '-----BEGIN PRIVATE KEY-----\\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDn8A2XsX/vYDOm\\nd79QhxHAaP8GTGX4ctPtTYzJNYJAAshG/3QddqHbb0Am6AaRalWygEYsEseqt1d9\\nV3BnckwCCjNEVKwLYlv3eutcDn9sRcXmIGXwmXTuvAnvnyj+8lawi0mghBufQBa5\\n0hBgtF053wuxmu4ez0ZbaGsQDX2Yxjnbx00aOdE+w6tS9OGgIS5ox2SFwdCuOCHp\\nooROVhdV2RKKf+tK3wvs/DTGo5IcNK5iBErHABqOVkmPY2HlWlDgDdALFfuNK8Zb\\n6OIdmSLL1Ywc6nhcu1OPnQPVVSRADG+Rpn3frnBrw7G2p/kobtRlXqPOXNevrKXG\\nW4otkv3ZAgMBAAECggEBAMd8GUTCHsYU2PexgLPTKDp0U/vn08Bnis1MaO1Z/2fs\\nvLML3aPFuBqSyftsjtGdQo3fc/tOP7seK7qbbQscLDGI8mUv6jV0aKMnbqzjr0bB\\nkB+I+ASDCCaZRnZ5TvpQFq2Lb00Gsvc6WRGDkiCKoLA4ncco+Os43UubOJI6+C5f\\nlJN9V6nKmVoFCGE2PBv4o3edu3A0wontCh+BwgWfWpBOQFn8SMLJ5MHk3XrkOxzV\\n06WB2/g/R3KPq3HdIkGTpZ5uDW8/FJDozd5z5Aep/2jP+VRbR8C9+sUKsMfBNbeB\\nWPuBVa//nvzFTSKBxkFuryWFTb7tKXN5UA4h7yZ3JIECgYEA9Ntll+w1PXX9N7c0\\nimQ39vTVsFcC82G6ja5/zMF/8xbHhgPVORYZhcNw1Nl9VSF+a3h81n/35nUkn9ou\\nfc8c7SoXpYO52iRZUZ5ZKJPf8TQWVJtQ48XE+3cZAKe9vNYTcuxVwOe30M+nNtYY\\nVuI1EZ8LX8SLRYYQrwnTJjIopLECgYEA8n4lMHnr6S2qodBujZHPA4W5T0taRIqU\\n4KauyeITyOWZPeZQ3iDUqLGKr+3LrD/0VtXBx9f26i79KWfghRlqNKwjs5Of5JsP\\ncB2rLnTBIdkBHsn8mzvqsBl4zMMr0ss36ySSRgQwKXFowfbVdDdjZpZKYrdcUAKj\\nZpGBTeTn1akCgYEAxvCGv4OT0ibOIHmCf3pjWgucntRjOlk52Clh/ntsuJXWcEUm\\n9WXGQM8FGnrGgOdgrnLLgv+f66dbpWEAiwk+qFadtcWrt9f2lgDA0d4rge7fAcjb\\nVOR3YhRmxQiEeSu5y5LHLZ9W0poUctJKHjVWBsYg2KN4wHjnjz+9RXhVW1ECgYEA\\nxq/5RMkBNSPHxaIEk1a/KgGtnnz9T1/FMHUijiQBVgBaGU/XPsnjtP0Tx6at1Urp\\npySqDFa155fssqBEJIp4bQQGlKMGxccPVSvaEMx1Woh11IZnxcHIP9X/Frdr9uGv\\nxalHeLsBw1M7JIJcz0Z62ZmXBV978crXm7jpG6vNEVECgYA1kFHLm/K0OW+lJNtq\\nRQsw7jXpIWfR3gr8MKudE3SJi/nX7/VZlIH9eCdEq5jg61dNTe3WZhHSUPF8fGyt\\n5qEScr1CttlEqkHLXWfaGeJI96On7B8BpYgFySiBu634uhb5yhMH27Y0V+416TeM\\nI/LBlLGVzdmTNu8gsM8v9ijQfQ==\\n-----END PRIVATE KEY-----\\n'
    PGRST_JWT_SECRET: '{"kty":"RSA","n":"5_ANl7F_72Azpne_UIcRwGj_Bkxl-HLT7U2MyTWCQALIRv90HXah229AJugGkWpVsoBGLBLHqrdXfVdwZ3JMAgozRFSsC2Jb93rrXA5_bEXF5iBl8Jl07rwJ758o_vJWsItJoIQbn0AWudIQYLRdOd8LsZruHs9GW2hrEA19mMY528dNGjnRPsOrUvThoCEuaMdkhcHQrjgh6aKETlYXVdkSin_rSt8L7Pw0xqOSHDSuYgRKxwAajlZJj2Nh5VpQ4A3QCxX7jSvGW-jiHZkiy9WMHOp4XLt1OPnQPVVSRADG+Rpn3frnBrw7G2p/kobtRlXqPOXNevrKXGluKLZL92Q","e":"AQAB"}'
    
defaultCert:
  enabled: true
  name: cert-hcce
  data:
    tls.crt: 'LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNyakNDQVpZQ0NRQ1N6V0Ftd3VXdzBqQU5CZ2txaGtpRzl3MEJBUXNGQURBWU1SWXdGQVlEVlFRRERBMXQKWlhSaExXaDFZbk11YjNKbk1DQVhEVEkyTURFeU5qQTNOVE0xTVZvWUR6SXhNall3TVRBeU1EYzFNelV4V2pBWQpNUll3RkFZRFZRUUREQTF0WlhSaExXaDFZbk11YjNKbk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBCk1JSUJDZ0tDQVFFQTE5aE9PbXAvR1dSMm5aVVZHN08zd0swSEFrZFAzaW05YTRIV25hMExldXNoWndRTWtnbFEKYVU5QTgxcE9qM0h1RWYvSmJSTlJzUCtRZGdOK3NObVJBVjFOaUtjbTZiR2wyNDdwRjNOSERBby9oSWlUY0dUMQpJeHFRQ0FpeTY0YkE0a2wvSHZvZHhoT2ExS1RyZmlScjJ0dWpaSEh4cE8xb0lLT2xFRThQbG9ML2VkUzJMTFpZClJXQ2cwOHorS1I3RVpYazFjVUQzU09uUW5lSXJ4aktYQ3pFdTdOWnZYQkNDTnJuendHUGE2dWtieS8zUDg0OTgKVGtDL1NJTENPaGZycEU4R2RLd1FQRmJiQXk2TlRPWmNRN0xBR055eHdnbkR5akJjaXBBVnBLSTdlWjBzTnh5Swo2S0hBaEN1VWlvRGlneEQ4d1RrdFRvU29IMEdYT216YzlRSURBUUFCTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCCkFRQXlGM0ptN1lOSjlPVjgrTTVwUi9YUk0zQ3F2dWZwcnBJSHdlbDcrY3QzOU1RNG1lb2RvY2BaZFZLQXJIbDAKMWF6WmlFQ0RlWXJRbWRGVzBFeTNUUXNMMm00S2x2ZWJxYWJTL21PK2U3bCtFWXBST0lzaElkSTRMRWRhcjhHZQpURklTZkM1QTlPa2xYR3luV3owUHc5UG5hVi9wQXYzNFV6SkJ2OXRqSW5EMlY1bFFmakhMd0Evc2RYMFl6NDU2CnIwWFZKL3R2L1EwOHpadmFvdWd2RFFWZzJSQVZQbXlQTUkyL3J5bEtzQmRCMlNhYWJIdmdjaHh1QmVFdmkyc1oKcnpBZFZBZC9yWkxxZFBXWmxzbGRVNWt6V3V3YXowVFNUNnFnUktBcGNIeEM0SlhmNXlNUEwzelNyVmZRc0hqRQpsWE8ybDJVcUhDT0dZMU9rSGg2cUxsNnkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo='
    tls.key: 'LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2d0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktrd2dnU2xBZ0VBQW9JQkFRRFgyRTQ2YW44WlpIYWQKbFJVYnM3ZkFyUWNDUjAvZUtiMXJnZGFkclF0NjY2eUZuQkF5U0NWQnBUMER6V2s2UGNlNFIsLzhsdEUxR3cvNUJSCkEzNncyWkVCSFcxSUlweWJwc2FYYmp1a1hjMGNNQ2orRWlKTndaUFVqR3BBSUNMTHJoc0RpU1g4ZStoM0dFNXJVCnBPdCtKR3ZhMjZOa2NmR2s3V2dnbzZVUVR3K1dndjk1MUxZc3RsaEZZS0RUelA0cEhzUmxlVFZ4UVBkSTZkQ2QKNGl2R01wY0xNUzdzMW05Y0VJSTJ1ZlBBWTlycTZSdkwvYy96ajN4T1FMOUlnc0k2Rit1a1R3WjByQkE4VnRzRApMbzFNNWx4RHNzQVkzTEhDQ2NQS01GeUtrQldrb2p0NW5TdzNISXJvb2NDRUs1U0tnT0tERVB6Qk9TMU9oS2dmClFaYzZiTnoxQWdNQkFBRUNnZ0VCQUk0K0FRZWtLUkJkMFlGMXZzeGJ1a3VpZTB6NEc5MG5tcW5mamNTcFJqaUIKL2FnNjFlSGplM2Q3QUMyZkpNaUpaeis3Vmsyb2ZweHJQeE5XcUVYNWl3TGdMdmxRVm1lSloranlIQkFWS3d2MwpNUGF4WHFDaUY1NURvZ2w1V2hlMjNTUURGV0FmcWtGZnFCaGNlc2pOVGJxVUpmQksydGs2anZWN2dvcmwzenJxCjhTWjY4MjZKWTM3aXJxWFo2Kyt0bW8yL0FpUG1EMjI0bVlhcy96bXNQUlgrUjdxZXRvSVhIL0grNDFIejZXL1gKMERzQW5FZm03dlk3OFhVckJuRk1FcFRNZjZGRDlmTmlXYmY0cG5JUm9Pd3V3bTZoTEhHczdTcDRFZW4rQ2tCVgpmRTVDOGllYkdCc29LZzR4TjVCU3czMmExdllxMWFubG9jOHNJd0FVRW1FQ2dZRUE5eEhwUldka1B2ZXUxVFFJCkVtaEtQR3Nmcmo2VmE4cjcyN3pWWFVwd1k3WDUyRHNUVmJXcGdZbXIwNG90eVVlcTBFeC9XaHdtdmxsQklRY0oKbnRmRFpMQ1J2R25sYzVvdU9TeTBFMGY3L2c3Q3puMGNRam9QMnlDSlNmV3VDVjZYTXNhSCsyTWd5KzRWRlQ2bApqdG52aUZ2NWl0YUx4R08vZmNJWXJwSEhlaWtDZ1lFQTM2VjV1cWREaEdTUlF6SHhQRlZLbmJ4SHZCQzE3QUR6CkNuUU5vWTR3cnZRL1FPQkhLeXF2NWVVblJpai9ZVXhFd3VVN3dkaU5SNDc2bFVyMXpPZ21uU3pCUTVVa2NxS3cKdmthV2RxajJkMGZzdTcvYUpId2Jkd21RSkp0RjVtczFyWmNtdGJNNkZpaHVvaW80VzBMS0xIUzNIdTA0c1piSgozSnZsWm5ZZFBlMENnWUVBenZSQjRkRHBNNVZnN1ZYWUxSTU9tKzFmYkNVZ0pGcXkvU3ovekZVK0wwZVBNSURMCmdVL1ozSmZsUmh6SW5ZRmFvNEJ3YkpxSUdZcHF4NitOYjNCc1N6dGIxK2NjTytrNkxzb3pUTE5QY1ZBTC9jcnUKa01yeDNTc3oxSy9tU0JManM3UjQweW9GbnN5ZS9GeXRjU3M4YVl3aFN4ckxtSVcxTVRJVVdxWGg0WUVDZ1lFQQpvSkRoVUl6K0FITmpoMmEzMTZVMHFRS2dUZm1CWXl0YlVzbjNiMkh5dWVsSjhINFZHbnpQUkxLOCs3WTdnOU9LCkdwTVIwQjUxY0ViS3laekQxSlZvQTdnNkdSZGV6NTdXWGdXM3lRR04waDJsYlRaVW01VXU4c3UrM1VsTmFoelcKc1Fhd0dBdlJURTlDL3RKcEc3eGNBb2JaWWk3V1lVbnRLNklSbFBxQURCRUNnWUFEMlFXT3BqNHpxY2xmV1JRMgpPd3JCK2VaT20xK2pXTnZsbU1rbWswTUlsSHkrTkxhckVvbWV6WW1jWmlQOTlheGZJcVU3T3Frakl3ZTlya1NtClZLT09BMnh6SFREY05MNnBrWXJTV2hHT1hYaGQ2Ym9Xc2d0YkhKUitTWWJodDlRcGRRYSt1ZE14NEVaaU9JaVUKTUhiOHJUelZha1dhTExiM3NjcDVJQ2hkeVE9PQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=='

reticulum:
  imagePullSecrets:
    - name: registry-meta-hubs-registry
  persistence:
    enabled: true
    size: 10Gi
    storageClass: do-block-storage
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 256Mi
  image:
    repository: registry.digitalocean.com/meta-hubs-registry/reticulum
    tag: "latest"

spoke:
  imagePullSecrets:
    - name: registry-meta-hubs-registry
  image:
    repository: registry.digitalocean.com/meta-hubs-registry/spoke
    tag: "latest"
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

pgsql:
  persistence:
    enabled: true
    size: 10Gi
    storageClass: do-block-storage
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 256Mi

