apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moz-reticulum-admin-rewrite
  namespace: hcce
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      rewrite ^/admin/(.*)$ /admin break;
    cert-manager.io/cluster-issuer: self-signed-issuer
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - meta-hubs.org
    secretName: moz-reticulum-tls
  rules:
  - host: meta-hubs.org
    http:
      paths:
      - path: /admin/(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: moz-reticulum
            port:
              number: 4000
