apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moz-reticulum-admin-rewrite
  namespace: hcce
  annotations:
    kubernetes.io/ingress.class: haproxy
spec:
  ingressClassName: haproxy
  tls:
  - hosts:
    - meta-hubs.org
    secretName: cert-meta-hubs.org
  rules:
  - host: meta-hubs.org
    http:
      paths:
      - path: /admin
        pathType: Prefix
        backend:
          service:
            name: moz-reticulum
            port:
              number: 4000
